### ISSUE TITLE
[Feature request] 关于 SwitchAppearance 组件

### ISSUE THREAD

**Issue by KomoriDev** [kongying-tavern/docs#217]
### Description

目前这个组件似乎有异常，并不能很好的遮住 Button，是否会考虑完善？
![image](https://github.com/kongying-tavern/docs/assets/110453675/bc57df29-bfda-4117-829d-43b8c695b3cd)

### Proposed Solution

暂无

**Comment by jiazengp** [comment]
无法复现，请提供系统和浏览器以及屏幕信息~

**Comment by KomoriDev** [comment]
操作系统：Windows 11 专业版 64位（10.0，版本 22621）
显示模式：1920 x 1080（32bit）(60Hz)
浏览器：Google Chrome（正式版本）

**Comment by jiazengp** [comment]
![image](https://github.com/kongying-tavern/docs/assets/86162890/ee6ad828-5e33-48a5-a597-acc1369f92ba)
以测试正常100%的缩放下，没有发现这个问题。请检查缩放是否为100%以及是否浏览器插件影响

**Comment by KomoriDev** [comment]
我在笔记本或是安卓手机上测试，依然有 “错位” 现象（100%缩放）

**Comment by jiazengp** [comment]
抱歉，我在我们群里面也问了均无人能复现。如果没有其他人反馈，这个问题暂时不会得到处理。
感谢你的反馈

**Comment by KomoriDev** [comment]
好的
